spring:
  application:
    name: Employee
    
  data:
    mongodb:
      uri: mongodb://mongodb/microserviceblog
      
---

spring:
  profiles: docker
  
  data:
    mongodb:
      uri: mongodb://mongodb/microserviceblog
#      host: mongodocker
#      port: 2020
#      database: microserviceblog
      